config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('goods.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path
from .views import *

app_name = 'goods'

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("all-products/", AllProductsView.as_view(), name="all_products"),
    path("product/<slug:slug>", ProductDetailView.as_view(), name="product_detail"),

    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="add_cart"),
    path("my-cart/", MyCartView.as_view(), name="my_cart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="manage_cart"),
    path("empty-cart/", EmptyCartView.as_view(), name="empty_cart"),

    path("check-out/", CheckoutView.as_view(), name="check_out"),
    path("register/", RegistrationView.as_view(), name="registration"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("login/", LoginView.as_view(), name="login"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/order-<int:pk>/", OrderDetailView.as_view(), name="order_detail"),
    path("search/", SearchView.as_view(), name="search"),

]

  

goods/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = "Покупатель"
        verbose_name_plural = "Покупатели"


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория")
    image = models.ImageField(upload_to="products", verbose_name="Изображение")
    marked_price = models.PositiveIntegerField(verbose_name="Цена")
    selling_price = models.PositiveIntegerField(verbose_name="Цена продажи")
    description = models.TextField(verbose_name="Описание")
    warranty = models.CharField(max_length=300, null=True, blank=True, verbose_name="Гарантия")
    return_policy = models.CharField(max_length=300, null=True, blank=True, verbose_name="Политка возврата")
    view = models.PositiveIntegerField(verbose_name="Обзоры")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"


class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)

    class Meta:
        verbose_name = "Корзина"
        verbose_name_plural = "Корзина"


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + "CartProduct: " + str(self.id)

    class Meta:
        verbose_name = "Продукт корзины"
        verbose_name_plural = "Продукты корзины"


ORDER_STATUS = (
    ("Заказ получен", "Заказ получен"),
    ("Заказ обрабатывается", "Заказ обрабатывается"),
    ("Заказ в пути", "Заказ в пути"),
    ("Заказ выполнен", "Заказ выполнен"),
    ("Заказ отменен", "Заказ отменен"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=20)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Order: " + str(self.id)

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

templates/about.html
{% extends "base.html" %}
{% block title %}О нас{% endblock %}


  {% block content %}
    <h1>Мы начинающие экономисты в городе</h1>
  {% endblock %}

templates/add_cart.html
  {% extends "base.html" %}

  {% block title %}Добавить в корзину{% endblock %}

  {% block content %}
    <div class="container">
      <h3>Товар успешно добавен в корзину </h3>
    </div>
{% endblock %}

templates/all_products.html
{% extends "base.html" %}
{% block title %} Все товары {% endblock %}

  {% block content %}
  <div class="container">
    <h3>Все товары</h3><hr>
    {% for cat in allcategories %}
    <h4>{{cat.title}}</h4>
    <div class="row">
      {% for p in cat.product_set.all %}
      <div class="col-md-3">
       <div class="m-4">
         <h3>{{p.title}}</h3>
         <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 2500; object-fit: cover;">
         <p class="mt-3">Цена:<strike>${{p.marked_price}}</strike> ${{p.selling_price}}</p>
         <a href="{%  url 'goods:add_cart' p.id %}" class="btn btn-primary">Добавить в корзину</a>
       </div>
      </div>
      {% endfor %}
    </div>
    {% endfor %}
  </div>
  {% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-info">
          <a class="navbar-brand" href="#"> Электронная продажа</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSup">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'goods:home' %}">Страница приветствия<span class="sr-only">(Действующий)</span></a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'goods:all_products' %}">Категории</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'goods:my_cart' %}">Корзина</a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Мой аккаунт
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if request.user.customer %}
                <a class="dropdown-item" href="{% url 'goods:profile' %}">Мой профиль</a>
                <a class="dropdown-item" href="{% url 'goods:logout' %}">Выход из системы</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'goods:registration' %}">Регистрация пользователя</a>
                <a class="dropdown-item" href="{% url 'goods:login' %}">Вход в систему</a>
                {% endif %}
              </div>
            </li>
          </ul>

          <form class="form-inline my-2 my-lg-0" action="{% url 'goods:search' %}" method="GET">
            <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Искать товары здесь..."
              aria-label="Search" required>
            <button class="btn btn-danger my-2 my-sm-0" type="submit">Поиск товаров</button>
          </form>
        </div>
      </div>
    </nav>
  <hr>

  {% block content %}
  {% endblock %}

<!-- JS script  -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

templates/check_out.html
  {% extends "base.html" %}

  {% block title %}Проверка{% endblock %}

  {% block content %}
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h3>Товары в корзине</h3>
          <a href="{% url 'goods:my_cart' %}">Обновить корзину</a>
          <table class="table">
            <thead>
              <th>СН</th>
              <th>Товар</th>
              <th>Цена</th>
              <th>Кол-во</th>
              <th>Пром резултат</th>
            </thead>
            <tbody>
              {% for cp in cart.cartproduct_set.all %}
                <tr>
                  <td>{{forloop.counter}}</td>
                  <td>{{cp.product.title}}</td>
                  <td>{{cp.rate}}</td>
                  <td>{{cp.quantity}}</td>
                  <td>{{cp.subtotal}}</td>
                </tr>
                {% endfor %}
                <tr>
                  <th colspan="5">Ощая стоимость</th>
                  <th>$ {{cart.total}}</th>
                </tr>
                </tbody>
              </table>
            </div>
          <div class="col-md-6">
          <h3>Форма проверки</h3>
          <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-info">Завершите заказ</button>
          </form>
        </div>
      </div>
    </div>
  {% endblock %}

templates/contact.html
{% extends "base.html" %}
{% block title %}Свяжитесь с нами{% endblock %}

  {% block content %}
    <h1>Свяжитесь с нами. Позвоните по следующим номерам</h1>
    <p>999999999999</p>
    <p>888888888888</p>
  {% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}Страница приветствия{% endblock %}

{% block content %}
  <div class="container">

     <h1 class="text-center">Добро пожаловать на сайт Интернет площадки</h1>
        <hr>
       <div class="row mt-3">
         {% for p in product_list %}
        <div class="col-md-3 card">
          <div class="m-4">
            <h4><a href="{%  url 'goods:product_detail' p.slug %}">{{p.title}}</a></h4>
            <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 200px; object-fit: cover;">
            <p class="mt-3"> Цена:<strike>${{p.marked_price}}</strike> ${{p.selling_price}}</p>
            <a href="{% url 'goods:add_cart' p.id %}" class="btn btn-primary">Добавить в корзину</a>
          </div>
        </div>
        {% endfor %}
    </div>
      <nav aria-label="...">
        <ul class="pagination">
            {% if product_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ product_list.previous_page_number }}">Предыдущая</a>
              </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Предыдущая</a>
            </li>
            {% endif %}

            {% for i in product_list.paginator.page_range %}
              {% if i == product_list.number %}
                <li class="page-item active"><a class="page-link">{{i}}</a></li>
              {% else %}
                <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
              {% endif %}
            {% endfor %}

            {% if product_list.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ product_list.next_page_number }}">Следующая</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Следующая</a>
              </li>
            {% endif %}
        </ul>
      </nav>

  </div>
  {% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}Логин покупателя {% endblock %}

{% block content %}
  <style>
    .errorlist{
      color: red;
    }
  </style>
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
          <h3>Вход в систему </h3>
          <hr>
          <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary">Вход в систему</button>
            {% if error %}
              <li style="color:red;">{{error}}</li>
            {% endif %}
          </form>
          <br>
          <p> или если нет аккаунта?<a href="{% url 'goods:registration' %}{% if request.Get.next%}
            ?next={{request.Get.next}}{% endif %}"> Зарегистрироваться здесь </a></p>
      </div>
    </div>
  </div>
{% endblock %}

templates/my_cart.html
   {% extends "base.html" %}

  {% block title %}Моя корзина{% endblock %}

  {% block content %}
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <h4>Товары в корзине </h4><hr>
          <table class="table">
            <thead>
              <th>СН</th>
              <th>Товар</th>
              <th>Цена</th>
              <th>Кол-во</th>
              <th>Пром резултат</th>
              <th>Действия</th>
            </thead>
            <tbody>
              {% for cp in cart.cartproduct_set.all %}
                <tr>
                  <td>{{forloop.counter}}</td>
                  <td>{{cp.product.title}}</td>
                  <td>{{cp.rate}}</td>
                  <td>{{cp.quantity}}</td>
                  <td>{{cp.subtotal}}</td>

                  <td class="col-md-8">
                    <a href="{% url 'goods:manage_cart' cp.id %}?action=inc" class="btn btn-primary">+</a>
                    <a href="{% url 'goods:manage_cart' cp.id %}?action=dcr" class="btn btn-warning">-</a>
                    <a href="{% url 'goods:manage_cart' cp.id %}?action=rmv" class="btn btn-danger">*</a>
                  </td>
                </tr>
              {% endfor %}
              <tr>
                <th colspan="5">Общая стоимость</th>
                <th>$ {{cart.total}}</th>
                {% if cart.cartproduct_set.all %}
                <th><a href="{% url 'goods:empty_cart' %}">Пустая Корзина</a></th>
                {% endif %}
              </tr>
              {% if cart.cartproduct_set.all %}
              <tr>
                <th><a class="btn btn-info" href="{% url 'goods:check_out' %}">Проверка</a></th>
              </tr>
              {% endif %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
{% endblock %}

templates/order_detail.html
{% extends "base.html" %}
{% load humanize %}

{% block title %} Детали товара {% endblock %}

  {% block content %}
  <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <h3>Детали заказа</h3><hr>
            <p><span class="font-weight-bold">ID Заказа: </span>#ORDER_ {{ord_obj.id}}</p>
            <p><span class="font-weight-bold">Статус Заказа: </span> {{ord_obj.order_status}}</p>
            <p><span class="font-weight-bold">Заказано: </span> {{ord_obj.created_at}}({{ord_obj.created_at|timesince }} назад)</p>
            <p><span class="font-weight-bold">Информация доставки:</span> К {{ord_obj.ordered_by}}, {{ord_obj.mobile }}</p>
            <p><span class="font-weight-bold">Адрес:</span> {{ord_obj.address}}, ({{ord_obj.email}})</p>
            <h4>Заказаные товары</h4>
            <table class="table">
              <thead>
                <tr>
                  <th>СН</th>
                  <th>Товары</th>
                  <th>Коэффициент</th>
                  <th>Кол-во</th>
                  <th>Сумма</th>
                </tr>
              </thead>
              <tbody>
              {% for cp in ord_obj.cart.cartproduct_set.all %}
                <tr>
                  <td>{{forloop.counter}}</td>
                  <td><a target="_blank" href="{% url 'goods:product_detail' cp.product.slug %}">{{cp.product.title}}</a></td>
                  <td>{{cp.rate}}</td>
                  <td>{{cp.quantity}}</td>
                  <td>{{cp.subtotal}}</td>
                </tr>
              {% endfor %}
              <tr>
              <th colspan="5" class="text-right">Общая стоимость:</th>
              <th>${{ord_obj.total|intcomma}}</th>
              </tr>
              </tbody>
          </table>
        </div>
      </div>
  </div>
  {% endblock %}

templates/product_detail.html
 {% extends "base.html" %}
{% block title %} {{product.title}} {% endblock %}

  {% block content %}
  <div class="container">
    <h3>Товар: {{product.title}}</h3><hr>
    <div class="row">
      <div class="col-md-6">
        <img src="{{ product.image.url }}" alt="" class="img-fluid">
      </div>
      <div class="col-md-6">
        <h4>{{product.title}}: Просмотры {{product.view}} </h4>
        <h5>Категория: {{product.category}}</h5>
        <h5>Цена: <strike> ${{product.marked_price}} </strike>
          ${{product.selling_price}} </h5>
        <a href="{% url 'goods:add_cart' product.id %}" class="btn btn-info">Добавить в корзину</a>
        <hr>
        <p class="text-info">Гарантия: {{product.warranty}}</p>
        <p class="text-info">Политика возврата: {{product.return_policy}}</p>
        <hr>
        <p>{{product.description}}</p>
      </div>
    </div>
  </div>
  {% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block title %}Мой профиль{% endblock %}

  {% block content %}
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h3>Подробная информация</h3><hr>
          <p><span class="font-weight-bold">Имя: </span> {{customer.full_name}}</p>
          <p><span class="font-weight-bold">Имя пользователя: </span> {{customer.user.username}}</p>
          <p><span class="font-weight-bold">Email: </span> {{customer.user.email}}</p>
          <p><span class="font-weight-bold">Адрес: </span> {{customer.address}}</p>
          <p><span class="font-weight-bold">Присоединился: </span> {{customer.joined_on}}</p>
        </div>
        <div class="col-md-8">
        <h3>Предыдущие заказы</h3>
        <hr>
          <table class="table">
            <thead>
              <tr>
                <th>СН</th>
                <th>ID Заказа</th>
                <th>Кол-во</th>
                <th>Заказано</th>
                <th>Статус</th>
              </tr>
            </thead>

            <tbody>
            {% for ord in orders %}
              <tr>
                <td>{{forloop.counter}}</td>
                <td><a href="{% url 'goods:order_detail' ord.pk %}">#ORDER_{{ord.id}}</a></td>
                <td>{{ord.total}}</td>
                <td>{{ord.created_at|timesince}} назад</td>
                <td>{{ord.order_status}}</td>
              </tr>
            {% endfor %}
            </tbody>

            </table>
          </div>
        </div>
      </div>
  {% endblock %}

templates/registration.html
  {% extends "base.html" %}

  {% block title %}Регистрация покупателя {% endblock %}

  {% block content %}
    <style>
      .errorlist{
        color: red;
      }
    </style>
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Форма регистрации покупателя</h3><hr>
            <form action="" method="POST">
              {% csrf_token %}
              {{form.as_p }}
              <button class="btn btn-primary" type="submit" name="registration">Регистрация пользователя</button>
            </form>
            <br>
            <p> уже есть аккаунт? <a href="{% url 'goods:login' %}"> Вход в систему</a></p>
        </div>
      </div>
    </div>
{% endblock %}

templates/search.html
{% extends "base.html" %}
{% block title %}Поиск{% endblock %}

  {% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3>Поиск резултатов по <span class="text-info"> {{request.GET.keyword}}</span></h3>
        <hr>
        {% for result in results %}
        <div class="row">
          <div class="col-md-4">
            <img src="{{result.image.url }}" class="img-fluid" alt="">
          </div>
          <div class="col-md-8">
            <h4><a href="{% url 'goods:product_detail' result.slug %}">{{result.title}}</a></h4>
            <p> {{result.description}}</p> <!-- truncatechars - обрезка до n символов и многоточие -->
            <p> Политика возврата: {{result.return_policy}}</p>
            <a href="{% url 'goods:add_cart' result.id %}" class="btn btn-primary">Добавить в 
              корзину</a>
          </div>
        </div>
        {%  endfor %}
      </div>
    </div>
  </div>
  {% endblock %}